### ISSUE TITLE
Possible upcoming problems using composer 2.0

### ISSUE THREAD

**Issue by jofranz** [systopia/de.systopia.xportx#11]
> **Deprecation warning: require.mk-j/PHP_XLSXWriter is invalid, it should not contain uppercase characters. Please use mk-j/php_xlsxwriter instead. Make sure you fix this as Composer 2.0 will error.**
> Loading composer repositories with package information
> Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
> Updating dependencies (including require-dev)
> Package operations: 1 install, 0 updates, 0 removals
>   - Installing mk-j/php_xlsxwriter (0.37): Downloading (100%)         
> Writing lock file
> Generating autoload files

**Comment by bjendres** [comment]
Thanks. Could you create a PR for the lower case composer file and verify that it works?

**Comment by jofranz** [comment]
Created a pull request GH-12
